### ISSUE TITLE
Add namespace fallback registry config

### ISSUE THREAD

**Issue by lann** [bytecodealliance/wasm-pkg-tools#36]
In order to support a more natural registry resolution algorithm for package dependencies, add new configuration for "namespace fallback registries". The resolution algorithm would look something like:

For a parent package fetched from registry R, pick the first available:
- Local (non-"fallback") registry mapping
- Registry R's advertised namespace mapping (ref #35)
- Fallback registry mapping

Question: Should packages published by Registry R itself be considered before fallbacks?

**Comment by calvinrp** [comment]
Probably better that the namespace mappings were explicitly specified in the registry metadata well-known. Instead of attempting to fetch other non-specified namespaces from the OCI registry and hope that they are correct if available.

**Comment by lukewagner** [comment]
For the first bullet (local registry mapping), I could imagine it being useful to have a sub-option that lets specify that the local registry is just an overlay, in the sense that: if a package-name is present in the local registry, use that; otherwise fall back.  This seems useful if, e.g., you're developing package `ba:a` and you need to patch a dependency `ba:b`, so you specify a local overlay for `ba` containing `b`, but everything else falls back to `bytecodealliance.org`.

**Comment by lann** [comment]
> specify a local overlay for ba containing b, but everything else falls back to bytecodealliance.org

The config does already have "package overrides" with I think can serve this purpose.

**Comment by lukewagner** [comment]
Nice!
